version: '3.9'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - db
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        INSTALL_PLAYWRIGHT: "false"
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    command: npm run dev
    environment:
      - NODE_ENV=development
    depends_on:
      - backend

  storybook:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        INSTALL_PLAYWRIGHT: "true"
    ports:
      - "6006:6006"
    volumes:
      - ./frontend:/app
    command: npm run storybook
    environment:
      - NODE_ENV=development
    depends_on:
      - backend

  db:
    image: postgres:15
    restart: always
    env_file:
      - ./backend/.env
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
