"""latest migration

Revision ID: f6042f76b143
Revises: faa0ed7e1074
Create Date: 2025-10-11 16:54:55.519333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6042f76b143'
down_revision: Union[str, Sequence[str], None] = 'faa0ed7e1074'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('flag_reason', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'flag_reason')
    # ### end Alembic commands ###
