"""latest migration

Revision ID: faa0ed7e1074
Revises: 71349741259f
Create Date: 2025-10-11 16:54:47.931711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'faa0ed7e1074'
down_revision: Union[str, Sequence[str], None] = '71349741259f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tttttt_id'), table_name='tttttt')
    op.drop_table('tttttt')
    op.drop_column('posts', 'flag_reason')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('flag_reason', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.create_table('tttttt',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('tttttt_pkey'))
    )
    op.create_index(op.f('ix_tttttt_id'), 'tttttt', ['id'], unique=False)
    # ### end Alembic commands ###
